config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users, :only => [:show]
  resources :listings
  root 'listings#index'
end

app/models/listing.rb
class Listing < ActiveRecord::Base
  belongs_to :user
  has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100#" }, default_url: "/images/:style/missing.png"
    validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :listings
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :configure_devise_permitted_parameters, if: :devise_controller?

  protected

  def configure_devise_permitted_parameters
    permitted_params = [:email, :password, :password_confirmation, :name, :location, :is_lender, :payment_url]

    if params[:action] == 'update'
      devise_parameter_sanitizer.for(:account_update) {
        |u| u.permit(permitted_params << :current_password)
      }
    elsif params[:action] == 'create'
      devise_parameter_sanitizer.for(:sign_up) {
        |u| u.permit(permitted_params)
      }
    end
  end

end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
  before_action :must_be_lender, only: [:new, :create, :update, :destroy]
  before_action :find_post, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]
  # before_action :authorized_user, only: [:edit, :update, :destroy]


  def index
    @tools = Listing.all.order('created_at DESC')
  end

  def new
    # @tool = Listing.new
    @tool = current_user.listings.build
  end

  def create
    @tool = current_user.listings.build(query_p)
    if @tool.save
      redirect_to @tool
    else
      render 'new'
    end
  end

  def show
    @tool = Listing.find(params[:id])
  end

  def edit
    @tool = Listing.find(params[:id])
  end

  def update
    @tool = Listing.find(params[:id])
    if @tool.update(query_p)
      redirect_to @tool
    else
      render 'edit'
    end
  end

  def destroy
    @tool.destroy
    respond_to do |format|
      format.html { redirect_to root_path, notice: 'Link was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def must_be_lender
    unless current_user && current_user.is_lender?
      redirect_to root_path, notice: "Some message"
    end
  end

  def find_post
    @tool = Listing.find(params[:id])
  end

  def query_p
    params.require(:listing).permit(:tool, :price, :location, :image)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/listings_helper.rb
module ListingsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ToolBox</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
</head>
<body>

<nav class="#ffa000 amber darken-2" role="navigation">
  <div class="nav-wrapper container">
    <a id="logo-container" href="/" class="brand-logo"><b>Tewl</b></a>
    <% if user_signed_in? %>
    <ul class="right hide-on-med-and-down">

      <% if current_user.is_lender %>
        <li><a href="/listings/new">Add a Tool</a></li>
      <% end %>

      <ul id="dropdown1" class="dropdown-content">
        <li><%= link_to 'Profile', current_user %></li>
        <li><a href="#">Messages</a></li>
        <li><%= link_to 'Settings', edit_user_registration_path %></li>
        <li class="divider"></li>
        <li><%= link_to "Sign Out", destroy_user_session_path, :method => :delete  %></li>
      </ul>
      <li><a class="dropdown-button" data-activates="dropdown1"><%= current_user.name %><i class="material-icons right">arrow_drop_down</i></a></li>
    </ul>
    <% else %>
    <ul class="right hide-on-med-and-down">
      <li><%= link_to "Sign In", new_user_session_path %></li>
      <li><%= link_to "Start Lending", new_user_registration_path %></li>
      <li><%= link_to "Start Borrowing", new_user_registration_path %></b></li>
    </ul>
    <% end %>
    <ul id="nav-mobile" class="side-nav">
      <li><a href="#">Navbar Link</a></li>
    </ul>
    <a href="#" data-activates="nav-mobile" class="button-collapse"><i class="material-icons">menu</i></a>
  </div>
</nav>

<% if notice %>
  <div id="notice-wrapper">
    <p class="notice"><%= notice %></p>
  </div>
<% elsif alert %>
  <div id="notice-wrapper">
    <p class="alert"><%= alert %></p>
  </div>
<% end %>

<br>
<br>
<br>

<%= yield %>

</body>

<script>
  $(document).ready(function() {
    setTimeout(function() {
      $('#notice-wrapper').fadeOut('slow', function() {
        $(this).remove();
      });
    }, 2000);
  });
</script>

</html>

app/views/listings/_tool.html.erb
<%= form_for @tool, html: { multipart: true } do |i| %>
  <%= i.label :tool %> <br>
  <%= i.text_field :tool %> <br>
  <br>
  <%= i.label :price %> <br>
  <%= i.text_field :price %> <br>
  <br>
  <%= i.label :image %> <br>
  <%= i.file_field :image %><br>
  <br>
  <%= i.submit %>
<% end %>

app/views/listings/edit.html.erb
<h2>Edit Tool Listing</h2>

<%= render 'tool' %>

app/views/listings/index.html.erb
<% @tools.each do |listing| %>
  <b><%= link_to listing.tool, listing %></b>
  <div><%= image_tag listing.image.url(:thumb) %></div>
  <div><%= listing.price %></div>
  <!--<div><%= listing.user.name if listing.user %></div> -->
  <div><%= link_to listing.user.name, listing.user %></div>
  <div><%= listing.user.location %></div>
  <div>Posted <%= time_ago_in_words(listing.created_at) %> ago</div>
  <br>
<% end %>

app/views/listings/new.html.erb
<h2>New Tool Listing</h2>
<%= render 'tool' %>

app/views/listings/show.html.erb
<h2><%= @tool.tool %></h2>
<div><%= image_tag @tool.image.url(:medium) %></div>
<div><b>Rental Price:</b> <%= @tool.price %></div>
<div><b>Lender location:</b> <%= @tool.user.location %></div>
<div><b>Payment link:</b> <%= @tool.user.payment_url %> </div>

<a class="waves-effect waves-light btn"><i class="material-icons right">swap_horiz</i>Rent</a>
<br>

<% if @tool.user == current_user %>
  <%= link_to 'Edit', edit_listing_path(@tool) %>
  <%= link_to 'Delete', listing_path(@tool), method: :delete, data: { confirm: "You are about to delete this listing" } %>
<% end %>

app/views/users/show.html.erb
<h1><%= @user.name %></h1>
<% if @user.is_lender %>
  <div>Lender</div>
<% else %>
  <div>Borrower</div>
<% end %>

<div>Rating: <%= @user.rating %></div>

<div><%= @user.location %></div>
<div><a href="#"><%= @user.payment_url %></a></div>